---
- hosts: all

  roles:
    - role: users
      tags: users, user, init, ssh, keys

    - role: common
      tags: common, apt, ufw

    - role: mail
      tags: mail, postfix

    # *certbot* is an additional role for certbot specific
    - role: apps
      tags: app, apps