---

- name: ansible.builtin.apt install
  become: yes
  
  ansible.builtin.apt:
    pkg: 
      - postfix
      - mailutils

      - postfix-policyd-spf-python
      
      - dovecot-core 
      - dovecot-imapd
      - dovecot-lmtpd
      
  notify: postfix reload

- include_tasks: certificate.yml
- include_tasks: postfix.yml
- include_tasks: opendkim.yml
- include_tasks: dovecot.yml