--- 

- name: ansible.builtin.copy /etc/mailname
  become: yes

  ansible.builtin.copy:
    dest: /etc/mailname
    content: mail.martijncasteel.nl

  notify: postfix reload

- 
  become: yes

  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'

  with_items:
    - src: postfix/main.cf
      dest: /etc/postfix/main.cf
    - src: postfix/master.cf
      dest: /etc/postfix/master.cf
  notify: postfix reload

- name: ansible.builtin.copy /etc/aliases
  become: yes

  ansible.builtin.copy:
    src: postfix/aliases
    dest: /etc/aliases
  register: output

- 
  become: yes
  ansible.builtin.shell: newaliases
  when: output.changed
  notify: postfix reload

- name: ansible.builtin.copy /etc/postfix/virtual
  become: yes

  ansible.builtin.copy:
    src: postfix/virtual
    dest: /etc/postfix/virtual
  register: output

- 
  become: yes
  ansible.builtin.shell: postmap /etc/postfix/virtual
  when: output.changed
  notify: postfix reload

- name: ansible.builtin.copy /etc/postfix/whitelist
  become: yes

  ansible.builtin.copy:
    src: postfix/whitelist
    dest: /etc/postfix/whitelist
  register: output

- 
  become: yes
  ansible.builtin.shell: postmap /etc/postfix/whitelist
  when: output.changed
  notify: postfix reload


- name: community.general.ufw
  become: yes

  community.general.ufw:
    rule: allow
    name: Postfix

  notify: postfix reload