---

- name: ansible.builtin.apt install python3-venv
  become: yes
  
  ansible.builtin.apt:
    name: python3-venv
    state: present

- name: ansible.builtin.pip
  ansible.builtin.pip: 
    requirements: '{{ item.dest }}/requirements.txt'

    virtualenv_command: python3 -m venv
    virtualenv: '{{ item.dest }}/env'

- name: 'ansible.builtin.template {{ item.systemd }}'
  become: yes

  ansible.builtin.template:
    src: templates/python.service.j2
    dest: '/etc/systemd/system/{{ item.systemd }}'

  when: item.systemd is defined

- name: 'ansible.builtin.systemd enable {{ item.systemd }}'
  become: yes

  ansible.builtin.systemd:
    name: '{{ item.systemd }}'

    daemon_reload: yes
    enabled: yes
    masked: no

    state: started
  
  when: item.systemd is defined