---

# - name: ansible.builtin.git
#   ansible.builtin.git:
#     repo: git@github.com:martijncasteel/marked-paper.git
#     dest: /var/www/martijncasteel.nl

- name: ansible.builtin.get_url development/build.tar.gz
  ansible.builtin.get_url:
    url: https://github.com/martijncasteel/marked-paper/releases/download/development/build.tar.gz
    checksum: sha512:https://github.com/martijncasteel/marked-paper/releases/download/development/checksum.sha512
    dest: /var/www/martijncasteel.nl
  register: output

- 
  ansible.builtin.unarchive:
    remote_src: yes
    src: /var/www/martijncasteel.nl/build.tar.gz
    dest: /var/www/martijncasteel.nl/
  when: output.changed


- name: ansible.builtin.set_fact
  ansible.builtin.set_fact:
    config:
      domains: 
        - martijncasteel.nl 
        - www.martijncasteel.nl 
        - martijncasteel.com 
        - www.martijncasteel.com

      root: /var/www/martijncasteel.nl/build

      csp: >- 
        default-src 'none'; 
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; 
        img-src 'self'; 
        font-src 'self' https://fonts.gstatic.com data:; 
        script-src 'self' https://code.jquery.com https://www.google-analytics.com; 
        media-src 'self'; 
        connect-src 'self' https://api.martijncasteel.com wss://api.martijncasteel.com;

      ssl:
        email: info@martijncasteel.nl
      

- include_tasks: ../tasks/host.yml
