---
# some common commands used after a clean install

- name: raspi-config do_change_locale
  become: yes
  command: raspi-config nonint do_change_locale en_US.UTF-8

- name: read /etc/default/keyboard
  shell: grep -Po '(?<=^XKBLAYOUT=\")\w*' /etc/default/keyboard 
  register: current_layout

- name: raspi-config do_configure_keyboard
  become: yes
  command: raspi-config nonint do_configure_keyboard us
  when: current_layout.stdout != "us"

- name: read /etc/timezone
  shell: cat /etc/timezone
  register: current_timezone

- name: ansible.builtin.copy /etc/timezone 
  become: yes
  ansible.builtin.copy: 
    content: Europe/Amsterdam
    dest: /etc/timezone

  notify: update tzdata
  when: current_timezone.stdout != "Europe/Amsterdam"
